apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::539643111082:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1UYWDHKC9P0EN
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::539643111082:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: '2022-07-13T09:25:22Z'
  name: aws-auth
  namespace: kube-system
  resourceVersion: '1757'
  uid: 59a1687e-c268-4d90-af96-8194e7c19fe7
